export default {
    user: {
        username: 'testUser',
        email: 'testuser@foo.com',
        loggedIn: false
    },
    restaurants: [
        {
            "id": "16915865",
            "name": "Franklin Barbecue",
            "description": "Long lines form early for brisket, pulled pork & other smoked meats at this lunch-only spot.",
            "url": "https://www.zomato.com/austin/franklin-barbecue-rosewood?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
              "address": "900 East 11th Street, Austin 78702",
              "hour": "8am-10pm",
              "locality": "Rosewood",
              "city": "Austin",
              "city_id": 278,
              "latitude": "30.2700861111",
              "longitude": "-97.7314611111",
              "zipcode": "78702",
              "country_id": 216,
              "locality_verbose": "Rosewood, Austin",
            "switch_to_order_menu": 0,
            "cuisines": "BBQ",
            "average_cost_for_two":'$$',
            "price_range": 2,
            "currency": "$",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/res_imagery/16915865_RESTAURANT_dcf726ac4b64ffc5331b907e78c7e38b_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
              "aggregate_rating": "4.7",
              "rating_text": "Excellent",
              "rating_color": "3F7E00",
              "rating_obj": {
                "title": {
                  "text": "4.7"
                },
                "bg_color": {
                  "type": "lime",
                  "tint": "800"
                },
              "votes": "543"
            },
            "photos_url": "https://www.zomato.com/austin/franklin-barbecue-rosewood/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/austin/franklin-barbecue-rosewood/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/res_imagery/16915865_RESTAURANT_dcf726ac4b64ffc5331b907e78c7e38b_c.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/16915865",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/austin/franklin-barbecue-rosewood/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
          },
        {
          
            "id": "16913120",
            "name": "Lamberts Downtown Barbecue",
            "description": "Fancy BBQ & other meaty fare in a refurbished general store with an upstairs bar with live music.",
            "url": "https://www.zomato.com/austin/lamberts-downtown-barbecue-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
              "address": "401 W 2nd Street, Austin 78701",
              "hour": "9am-10pm",
              "locality": "Downtown",
              "city": "Austin",
              "city_id": 278,
              "latitude": "30.2652694444",
              "longitude": "-97.7477583333",
              "zipcode": "78701",
              "country_id": 216,
              "locality_verbose": "Downtown, Austin",
            "switch_to_order_menu": 0,
            "cuisines": "BBQ",
            "average_cost_for_two": '$$$',
            "price_range": 4,
            "currency": "$",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/res_imagery/16913120_RESTAURANT_b69662f8388f5589492b547539227330_c.jpeg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
              "aggregate_rating": "4.2",
              "rating_text": "Very Good",
              "rating_color": "5BA829",
              "rating_obj": {
                "title": {
                  "text": "4.2"
                },
                "bg_color": {
                  "type": "lime",
                  "tint": "700"
                },
              "votes": "430"
            },
            "photos_url": "https://www.zomato.com/austin/lamberts-downtown-barbecue-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/austin/lamberts-downtown-barbecue-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/res_imagery/16913120_RESTAURANT_b69662f8388f5589492b547539227330_c.jpeg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/16913120",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/austin/lamberts-downtown-barbecue-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
          },
        {
          
            "id": "16913976",
            "name": "Stubb's Bar-B-Q",
            "description": "Beer, brisket and music Downtown with a renowned Sunday gospel brunch.",
            "url": "https://www.zomato.com/austin/stubbs-bar-b-q-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
              "address": "801 Red River Street, Austin 78701",
              "hour": "10am-10pm",
              "locality": "Downtown",
              "city": "Austin",
              "city_id": 278,
              "latitude": "30.2685250000",
              "longitude": "-97.7364416667",
              "zipcode": "78701",
              "country_id": 216,
              "locality_verbose": "Downtown, Austin",
            "switch_to_order_menu": 0,
            "cuisines": "BBQ",
            "average_cost_for_two": '$$',
            "price_range": 2,
            "currency": "$",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/res_imagery/16913976_RESTAURANT_3085724bc5247187d304f9a483fb6049_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
              "aggregate_rating": "3.9",
              "rating_text": "Good",
              "rating_color": "9ACD32",
              "rating_obj": {
                "title": {
                  "text": "3.9"
                },
                "bg_color": {
                  "type": "lime",
                  "tint": "600"
                },
              "votes": "378"
            },
            "photos_url": "https://www.zomato.com/austin/stubbs-bar-b-q-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/austin/stubbs-bar-b-q-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/res_imagery/16913976_RESTAURANT_3085724bc5247187d304f9a483fb6049_c.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/16913976",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/austin/stubbs-bar-b-q-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
          },
        {
          
            "id": "16915533",
            "name": "La Condesa",
            "description": "Contemporary Mexican dishes, a vast tequila selection & happy-hour deals in a sophisticated setting.",
            "url": "https://www.zomato.com/austin/la-condesa-downtown?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1",
              "address": "400 A W 2nd Street, Austin 78701",
              "hour": "10am-11pm",
              "locality": "Second Street District, Downtown",
              "city": "Austin",
              "city_id": 278,
              "latitude": "30.2656391000",
              "longitude": "-97.7477811000",
              "zipcode": "78701",
              "country_id": 216,
              "locality_verbose": "Second Street District, Downtown, Austin",
            "switch_to_order_menu": 0,
            "cuisines": "Mexican",
            "average_cost_for_two": '$$$',
            "price_range": 3,
            "currency": "$",
            "offers": [],
            "opentable_support": 0,
            "is_zomato_book_res": 0,
            "mezzo_provider": "OTHER",
            "is_book_form_web_view": 0,
            "book_form_web_view_url": "",
            "book_again_url": "",
            "thumb": "https://b.zmtcdn.com/data/res_imagery/16915533_RESTAURANT_8da689e573a00ddedc13441e53b0bf27_c.jpg?fit=around%7C200%3A200&crop=200%3A200%3B%2A%2C%2A",
              "aggregate_rating": "3.7",
              "rating_text": "Good",
              "rating_color": "9ACD32",
              "rating_obj": {
                "title": {
                  "text": "3.7"
                },
                "bg_color": {
                  "type": "lime",
                  "tint": "600"
                },
              "votes": "268"
            },
            "photos_url": "https://www.zomato.com/austin/la-condesa-downtown/photos?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1#tabtop",
            "menu_url": "https://www.zomato.com/austin/la-condesa-downtown/menu?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1&openSwipeBox=menu&showMinimal=1#tabtop",
            "featured_image": "https://b.zmtcdn.com/data/res_imagery/16915533_RESTAURANT_8da689e573a00ddedc13441e53b0bf27_c.jpg",
            "has_online_delivery": 0,
            "is_delivering_now": 0,
            "include_bogo_offers": true,
            "deeplink": "zomato://restaurant/16915533",
            "is_table_reservation_supported": 0,
            "has_table_booking": 0,
            "events_url": "https://www.zomato.com/austin/la-condesa-downtown/events#tabtop?utm_source=api_basic_user&utm_medium=api&utm_campaign=v2.1"
          }       
      ]
  };